# Generated by Django 4.1.5 on 2023-05-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0007_organisation_organisation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationaladmin',
            name='fields',
        ),
    ]
